apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-deployment
  namespace: wiremock
spec:
  replicas: 2
  selector:
    matchLabels:
      someLabel: wiremock-label
      #the key value pair of label can be anything we just need to make sure it matches the label
  template:
    metadata:
      labels:
        someLabel: wiremock-label
    spec:
      containers:
        - name: my-wiremock-app
          image: wiremock/wiremock:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: wiremock-file-storage
              mountPath: /home/wiremock/__files
      volumes:
        - name: wiremock-file-storage
          persistentVolumeClaim:
            claimName: wiremock-pv-claim
# no need to give name and namespace to the pod