apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiremock-pv
  labels:
    env: wiremock-pv-label
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/souvikchakraborty/Documents/projects/devtools/KubernetesPractice/wiremock-with-volume/files"